version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/bank_accounting
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres@db:5432/bank_accounting_development
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bank_accounting_development

volumes:
  postgres_data:
